# Generated by Django 2.1.1 on 2018-10-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ship',
            old_name='register',
            new_name='registers',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='call_sign',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='use',
        ),
        migrations.AddField(
            model_name='ship',
            name='uses',
            field=models.ManyToManyField(blank=True, to='atlas.Use', verbose_name='Current Use(s)'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='beam',
            field=models.FloatField(blank=True, null=True, verbose_name='Beam (m)'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='Length (m)'),
        ),
    ]
