# Generated by Django 2.1.1 on 2018-11-12 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0002_auto_20181025_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atlas.City', verbose_name='Location - City'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atlas.Country', verbose_name='Location - Country'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
