# Generated by Django 2.1.1 on 2018-11-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0003_auto_20181112_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='imo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='IMO Number'),
        ),
    ]
