# Generated by Django 2.1.1 on 2018-11-14 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0005_ship_mmsi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='mmsi',
        ),
        migrations.AddField(
            model_name='ship',
            name='fleetmon',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='FleetMon ID'),
        ),
    ]
