# Generated by Django 2.1.1 on 2018-11-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0006_auto_20181114_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='flag',
            name='flag',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='register',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='use',
            name='use',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='builder',
            unique_together={('builder_name', 'builder_city', 'builder_country')},
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('city_name', 'city_region')},
        ),
    ]
