# Generated by Django 2.1.1 on 2018-11-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0007_auto_20181119_0700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='builder',
            old_name='builder_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='builder',
            old_name='builder_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='builder',
            old_name='builder_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='city_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='city_region',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='flag',
            old_name='flag',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='register',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='status',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='use',
            old_name='use',
            new_name='name',
        ),
        migrations.AddField(
            model_name='builder',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='flag',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ship',
            name='slug',
            field=models.SlugField(max_length=205, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='status',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='use',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='builder',
            unique_together={('name', 'city', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'region')},
        ),
    ]
