# Generated by Django 2.1.1 on 2018-11-19 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0008_auto_20181119_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='flag',
        ),
        migrations.DeleteModel(
            name='Flag',
        ),
    ]
